spring:
  application:
    name: gateway
  management:
    endpoints:
      web:
        exposure:
          include: gateway

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://USER
          predicates:
            - Path=/api/user/**
          # filters:
          #   - AddRequestHeader=Hello, World