spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: gateway, info, health

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://USER
          predicates:
            - Path=/api/user/**
          # filters:
          #   - AddRequestHeader=Hello, World

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080
