spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # Optional: set to true to allow routing with lowercase service IDs
          lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
    # Optional: set to false to prevent the gateway itself from registering in Eureka
    # registerWithEureka: false 

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      # access: read-only
      enabled: true # Explicitly enable the gateway endpoint (default is true)


logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080
