spring:
  application:
    name: gateway
  cloud:
    gateway:
      # actuator-enabled: true
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user/**
          # filters:
          #   - AddRequestHeader=Hello, World

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      # access: read-only
      enabled: true # Explicitly enable the gateway endpoint (default is true)


logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080
