spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          # filters:
          #   - AddRequestHeader=Hello, World