spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://USER
              predicates:
                - Path=/api/user/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      # access: read-only
      enabled: true # Explicitly enable the gateway endpoint (default is true)

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    fetchRegistry: true  
    registerWithEureka: true 
    instance:
    prefer-ip-address: true