spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: gateway, info, health
  endpoint:
    gateway:
      enabled: true # Explicitly enable the gateway endpoint (default is true)

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user/**
          # filters:
          #   - AddRequestHeader=Hello, World

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080
