spring:
  application:
    name: gateway
  management:
    endpoints:
      web:
        exposure:
          include: gateway, info
    endpoint:
      info:
        enabled: true

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://USER
          predicates:
            - Path=/api/user/**
          # filters:
          #   - AddRequestHeader=Hello, World

logging:
  level:
    org.springframework.web: DEBUG
