spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: host.docker.internal:user:8081
          predicates:
            - Path=/api/user
          # filters:
          #   - AddRequestHeader=Hello, World