spring:
  application:
    name: school
  datasource:
    url: jdbc:postgresql://localhost:5433/cs_school_db
    username: dbcsuser
    password: 654321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    fetchRegistry: true  
    registerWithEureka: true 
  instance:
    prefer-ip-address: true

logging:
  level:
    com.dlucchesi.cloudschool.user: DEBUG

cloudschool:
  jwt:
    secret: s3cr3tK3yForJWTsN33dsToBeV3ryL0ngAndS3cur3F0rHS512Alg0r1thmPl3as3Ch4ng3M3L4t3rDontUseInProd=
    expiration-ms: 86400000
  school:
    nameMinLength: 8
    nameMaxLength: 50
    cnpjValidRegex: ^[A-Z0-9]{12}$
  loginRedirect: /