spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/cs_user_db
    username: dbcsuser
    password: 654321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081
