spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/cs_user_db
    username: dbcsuser
    password: 654321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    fetchRegistry: true  
    registerWithEureka: true 
  instance:
    prefer-ip-address: true

logging:
  level:
    com.dlucchesi.cloudschool.user: DEBUG

cloudschool:
  user:
    nameMinLength: 10
    nameMaxLength: 100
    passwordMinLength: 10
    passwordValidRegex: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=!]).*$}
    schoolMinLength: 8
    schoolMaxLength: 50
    cnpjValidRegex: ^[A-Z0-9]{12}$
    initUserAdmin: admin

